# VulnArk 生产环境配置文件
# ⚠️  安全提醒：
# 1. 请修改默认的JWT密钥和数据库密码
# 2. 确保此配置文件的权限设置为600 (chmod 600 config.prod.yaml)
# 3. 不要将包含真实密码的配置文件提交到版本控制系统

server:
  host: "0.0.0.0"  # 监听所有接口
  port: "8080"
  mode: "release"  # 生产模式
  read_timeout: 120
  write_timeout: 120

# CORS跨域配置 - 生产环境
cors:
  enabled: true
  allowed_origins:
    - "*"  # 生产环境根据实际需要配置具体域名
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
    - "HEAD"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Length"
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
    - "Accept"
  exposed_headers:
    - "Content-Length"
    - "Content-Type"
    - "Authorization"
  allow_credentials: true
  max_age: 43200

database:
  host: "${DB_HOST:localhost}"
  port: ${DB_PORT:3306}
  username: "${DB_USERNAME:root}"
  password: "${DB_PASSWORD:123456}"
  database: "${DB_NAME:vulnark}"
  charset: "utf8mb4"

jwt:
  secret: "${JWT_SECRET:ky6oJtR8MlYpMzJxhaVjWI1O4yeVUbkIJkJdGBzUt89lWifjWuZ1VDgqi68ciRKU}"
  expire_time: ${JWT_EXPIRE:3600}

oss:
  provider: "${OSS_PROVIDER:local}"
  access_key_id: "${OSS_ACCESS_KEY_ID:}"
  access_key_secret: "${OSS_ACCESS_KEY_SECRET:}"
  bucket: "${OSS_BUCKET:vulnark-files}"
  endpoint: "${OSS_ENDPOINT:}"
  region: "${OSS_REGION:}"

email:
  host: "${EMAIL_HOST:smtp.qq.com}"
  port: ${EMAIL_PORT:587}
  username: "${EMAIL_USERNAME:}"
  password: "${EMAIL_PASSWORD:}"
  from: "${EMAIL_FROM:}"

storage:
  type: "${STORAGE_TYPE:local}"
  local_path: "${STORAGE_LOCAL_PATH:./uploads}"
  base_url: "${STORAGE_BASE_URL:/uploads}"

log:
  level: "${LOG_LEVEL:info}"
  format: "${LOG_FORMAT:json}"
  output: "${LOG_OUTPUT:stdout}"