# VulnArk 开发环境配置文件
# 复制此文件并重命名为 config.yaml 以在开发环境中使用

# 应用基本信息
app:
  name: "VulnArk"
  version: "1.0.0"
  description: "漏洞管理平台"

# 服务器配置
server:
  host: "127.0.0.1"  # 开发环境只监听本地
  port: "8080"
  mode: "debug"  # debug模式用于开发
  read_timeout: 60
  write_timeout: 60

# CORS跨域配置 - 开发环境
cors:
  enabled: true
  allowed_origins:
    - "http://localhost:3000"    # React开发服务器
    - "http://127.0.0.1:3000"    # React开发服务器
    - "http://localhost:5173"    # Vite开发服务器
    - "http://127.0.0.1:5173"    # Vite开发服务器
    - "http://localhost:8080"    # 本地访问
    - "http://127.0.0.1:8080"    # 本地访问
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
    - "HEAD"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Length"
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
    - "Accept"
    - "Cache-Control"
  exposed_headers:
    - "Content-Length"
    - "Content-Type"
    - "Authorization"
  allow_credentials: true
  max_age: 3600  # 1小时，开发环境较短

# 数据库配置
database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  database: "vulnark"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

# JWT配置
jwt:
  secret: "vulnark-dev-secret-key-change-in-production"
  expire_time: 86400  # 24小时

# OSS配置
oss:
  endpoint: ""
  access_key_id: ""
  access_key_secret: ""
  bucket_name: ""

# 存储配置
storage:
  type: "local"
  local_path: "./uploads"
  base_url: "http://localhost:8080/uploads"

# 邮件配置
email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  username: ""
  password: ""
  from: ""

# 日志配置
log:
  level: "debug"  # 开发环境使用debug级别
  format: "text"
  output: "stdout"
  file_path: "./logs/app.log"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true
